# Generated by Django 5.2.4 on 2025-09-02 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0002_taskqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CLIENT', 'Report Client'), ('TASKER', 'Report Tasker')], max_length=12)),
                ('category', models.CharField(choices=[('conduct', 'Conduct / Behavior'), ('harassment', 'Harassment / Abuse'), ('spam', 'Spam / Scam'), ('fraud', 'Fraud / Payment'), ('quality', 'Poor Quality'), ('no_show', 'No show / Late'), ('safety', 'Safety Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED_UPHELD', 'Resolved (Upheld)'), ('RESOLVED_REJECTED', 'Resolved (Rejected)'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='task.task')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='report/files/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='report.report')),
            ],
            options={
                'db_table': 'report_attachment',
            },
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='report.report')),
            ],
            options={
                'db_table': 'report_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['task', 'status'], name='report_task_id_49b3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='report_reporte_250e97_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user'], name='report_reporte_453ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type'], name='report_type_9eba38_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='report_created_2a12c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='report_reporter_not_target'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW'])), fields=('reporter', 'reported_user', 'task', 'type'), name='uniq_open_report_per_pair_task_type'),
        ),
        migrations.AddIndex(
            model_name='reportattachment',
            index=models.Index(fields=['report', '-uploaded_at'], name='report_atta_report__ac76b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevent',
            index=models.Index(fields=['report', '-created_at'], name='report_even_report__42268a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevent',
            index=models.Index(fields=['event'], name='report_even_event_1bc7eb_idx'),
        ),
    ]
