# Generated by Django 5.2.4 on 2025-09-02 03:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0002_taskqr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('TASKER', 'Tasker')], help_text='Vai trò của reviewer trong task này', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Điểm đánh giá từ 1–5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewee', models.ForeignKey(help_text='Người được review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Người viết review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Review này thuộc về Task nào', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='task.task')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'indexes': [models.Index(fields=['reviewee'], name='review_reviewe_c98ebd_idx'), models.Index(fields=['task'], name='review_task_id_dbc50a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range_1_5')],
                'unique_together': {('task', 'reviewer', 'role')},
            },
        ),
    ]
