# Generated by Django 5.2.4 on 2025-09-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
